### ISSUE TITLE
cios group base count not updated to account for addition of Wii IOS59

### ISSUE THREAD

**Issue by seangibbz** [Leseratte10/d2xl-cios#2]
Line 3 of `data/ciosciosmaps.xml` should be updated for the appropriate amount of base options (i.e. 16).

Before:
```	<ciosgroup name="d2xl-v${MAJOR_VER}-${MINOR_VER}" version="${IOS_REV}" basescount="15">```

After:
```	<ciosgroup name="d2xl-v${MAJOR_VER}-${MINOR_VER}" version="${IOS_REV}" basescount="16">```

**Comment by fancythedeveloper** [comment]
Make a PR, then

**Comment by Leseratte10** [comment]
Thanks, I've merged the related PR #3.
